version: '3.3'

services:
  cocktailabend:
      image: cocktailabend
      build:
        context: ./
      ports: ['8080:8080']
      networks:
        - webnet
      links:
        - "mysql"
  mysql:
      image: mysql/mysql-server:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cocktails
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
      ports: ['42333:3306']
      networks:
        - webnet

networks:
  webnet:
    driver: bridge