version: '3.3'

services:
  cocktailabend:
      image: notmyfaultsir/cocktailabend:1.1
#      image: cocktailabend
      build:
        context: ./
      ports:
        - 8080:8080
      restart: on-failure
  mysql:
      image: mysql/mysql-server:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cocktails
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
      expose:
        - 3306
      restart: on-failure